name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Gerar estatísticas do GitHub
        run: |
          curl -o dist/github-stats.svg "https://github-readme-stats.vercel.app/api?username=guicardilho&show_icons=true&theme=dark&count_private=true&include_all_commits=true&hide_border=false&token=${{ secrets.GH_STATS_TOKEN }}"
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update GitHub stats [skip ci]"
          git push
