name: GitHub Stats Generator

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Criar diretório dist
        run: mkdir -p dist

      - name: Gerar estatísticas do GitHub
        run: |
          curl -o dist/github-stats.svg "https://github-readme-stats.vercel.app/api?username=seu-usuario&theme=dark&show_icons=true&hide_border=false&count_private=true"

      - name: Deploy para o branch output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update GitHub Stats [skip ci]"
